routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StudentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('student', StudentController::class);

app/Models/AssetLookup.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AssetLookup extends Model
{
    use HasFactory;
}

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Student extends Model
{
    use HasFactory,SoftDeletes;

    public $sortable = ['student_name', 'student_email'];

    protected $table = 'student';
    protected $primaryKey = 'student_id';

    protected $fillable = ['student_name','student_mykad','student_gender'];


    public function scopeFilter($query, $filters) {
        $query->when($filters['student_name'] ?? false, function($query, $search){
            $query->where('student_name', 'like', "%$search%");
        });
        $query->when($filters['student_mykad'] ?? false, function($query, $search){
            $query->where('student_mykad', 'like', "%$search%");
        });
    }


}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Student;
use Illuminate\Http\Request;
use App\Helpers\BankStatusHelper;
use Illuminate\Contracts\Session\Session;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        

        // ->sortable()


      $d['student']=  Student::filter(request(['student_name', 'student_mykad']))->paginate(10);

      
        //
        return view('student.index',$d);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $d['gender']=  BankStatusHelper::getGender();


        return view('student.create',$d);
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
 

        $validate = $request->validate([
            'student_name' => 'required',
            'student_mykad' => 'required',
            'student_gender'=> 'required',
        ],[
            'student_name.required' => 'Nama Adalah Diperlukan',
            'student_mykad.required' => 'student_mykad Adalah Diperlukan',
            'student_gender.required' => 'student_mykad Adalah Diperlukan'
        ]);

        // $validate['student_gender']=$request->input('student_gender');

        // dd($validate);


        try {

            // $student = Student::find($id);

            // dd($student);
            

            Student::create($validate);
            return redirect(route('student.index'))->withSuccess('Berjaya Kemaskini');
        } catch (\Throwable $th) {

            dd($th);
            return back()->withError('Something when wrong!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

       $student= Student::find($id);

    //    $student=Student::where(['student_gender'=>'M'])->get();

        dd($student);
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $d['gender']=  BankStatusHelper::getGender();
        $d['student']= Student::find($id);
        // dd($student);

        return view('student.edit',$d);
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Student $student)
    {
        $validate = $request->validate([
            'student_name' => 'required',
            'student_mykad' => 'required',
        ],[
            'student_name.required' => 'Nama Adalah Diperlukan',
            'student_mykad.required' => 'student_mykad Adalah Diperlukan'
        ]);
        try {

            // $student = Student::find($id);

            // dd($student);

            $student->update($validate);
            return redirect(route('student.index'))->withSuccess('Berjaya Kemaskini');
        } catch (\Throwable $th) {

            // dd($th);
            return back()->withError('Something when wrong!');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        try {

             $student->delete();
        //    $student= Student::find($id);
        //    $user->delete();
           return redirect(route('student.index'))->withSuccess('Berjaya Kemaskini');
           
        } catch (\Throwable $th) {
            dd($th);

            return back()->withError('Something when wrong!');
            
        }

    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Sticky Footer Navbar Template · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sticky-footer-navbar/">

    

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="sticky-footer-navbar.css" rel="stylesheet">
  </head>
  <body class="d-flex flex-column h-100">
    
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Fixed navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
</header>
<style>

main > .container {
  padding: 60px 15px 0;
}
</style>

<!-- Begin page content -->

<main class="flex-shrink-0">
    <div class="container">
        @yield('content')
    </div>
  </main>
  



<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>

<script src="https://code.jquery.com/jquery-3.6.4.slim.js" integrity="sha256-dWvV84T6BhzO4vG6gWhsWVKVoa4lVmLnpBOZh/CAHU4=" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

@yield('footer-scripts')

  </body>
</html>

resources/views/student/_form.blade.php
<div class="mb-3">
    <label for="student_name" class="form-label">student_name</label>
    <input value='{{old('student_name')??($student->student_name??'')}}' type="text" name='student_name' class="form-control" id="student_name" aria-describedby="emailHelp">
    
  </div>
  <div class="mb-3">
    <label for="student_mykad" class="form-label">student_mykad</label>
    <input value='' type="text"  name='student_mykad' class="form-control @error('student_mykad') is-invalid @enderror " id="student_mykad" >
    @error('student_mykad')
    <span class="invalid-feedback" role="alert">
     {{$message}}
    </span>
    @enderror


  </div>

  <div class="mb-3">
    <label for="student_gender" class="form-label">student_gender</label>

    <select id='student_gender' name='student_gender' class="form-select  @error('student_gender') is-invalid @enderror" aria-label="Default select example">
        <option selected>Open this select menu</option>
        @foreach ($gender as $key=>$item)
        <option {{(($student->student_gender??'')==$key?'selected':'')}}     value="{{$key}}">{{$item}}</option>
        @endforeach
        
    
        
      </select>
   
    @error('student_gender')
    <span class="invalid-feedback" role="alert">
     {{$message}}
    </span>
    @enderror


  </div>



  <div id='colordiv' class="mb-3">

    <label for="color" class="form-label">color</label>
    <input value='' type="text"  name='color' class="form-control @error('color') is-invalid @enderror " id="color" >
    @error('color')
    <span class="invalid-feedback" role="alert">
     {{$message}}
    </span>
    @enderror


  </div>




  @section('footer-scripts')

<script>
  $(document).ready(function(){
    $('#colordiv').hide();

  var genderdefault=  $(student_gender).val();


  hidecollor(genderdefault);





  
    $('#student_gender').on("change",
     function(){

  
     var gender= $(this).val();
     
  hidecollor(gender);


    });

    

    

  }); // end of docreadt
  

  function hidecollor(gender){

  
    if(gender=='M'){

$('#colordiv').hide();

}else if(gender=='F'){

$('#colordiv').show();
}
  }
  
  

</script>



  @endsection

resources/views/student/create.blade.php
@extends('layouts.app')


@section('content')


<form action="{{ route('student.store') }}" method="POST">
    @csrf


    @include('student._form')


    
    <button type="submit" class="btn btn-primary">Submit</button>

  </form>

  @endsection

resources/views/student/edit.blade.php
@extends('layouts.app')


@section('content')


<form action="{{ route('student.update',$student) }}" method="POST">
    @csrf
    @method('put')

    @include('student._form')


    
    <button type="submit" class="btn btn-primary">Submit</button>

  </form>

  @endsection

resources/views/student/index.blade.php
@extends('layouts.app')


@section('content')


<form>
    <div class="mb-3">
      <label for="student_name" class="form-label">student_name</label>
      <input value='{{request('student_name')}}' type="text" name='student_name' class="form-control" id="student_name" aria-describedby="emailHelp">
      
    </div>
    <div class="mb-3">
      <label for="student_mykad" class="form-label">student_mykad</label>
      <input value='{{request('student_mykad')}}' type="text" name='student_mykad' class="form-control" id="student_mykad">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>

  </form>

  <div class='text-center'>

  <a  href="{{route('student.create')}}" type="button" class="btn btn-primary">add</a>
  </div>

<table class='table'>
    <tr>
        <th>student name</th>
        <th>student mykad</th>
        <th>action</th>
    </tr>


@foreach ($student as $item)

<tr>
    <td>{{$item->student_name}}</td>
    <td>{{$item->student_mykad}}</td>
    <td>
        
        <a  href="{{route('student.show',$item)}}" type="button" class="btn btn-primary">view</a>
        <a  href="{{route('student.edit',$item)}}"  type="button" class="btn btn-info">update</a>
        <form  method='post' action="{{ route('student.destroy',$item) }}">
          @csrf
          @method('delete')
          <button type="submit" class="btn btn-danger">delete</button>
        </form>


    
    </td>
</tr>

    
@endforeach

</table>

{{ $student->appends(request()->except('page'))->links() }}

@endsection